Update error main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,3 +11,6 @@ jobs:
 
      - name: Run a sample Github action
        run: echo "workflow ran successfully for this action"
+
+     - name: Simulating error
+       run: echo "error simulated"; exit 1
